## SPDX-License-Identifier: Zlib

SOURCES += arch/x86_64/src/bxcon.c
SOURCES += arch/x86_64/src/gdt.c
SOURCES += arch/x86_64/src/idt.c
SOURCES += arch/x86_64/src/idt_thunks.S
SOURCES += arch/x86_64/src/intreq.c
SOURCES += arch/x86_64/src/setup.c
