/* SPDX-License-Identifier: Zlib */
#ifndef INCLUDE_VEX_VPROT_H
#define INCLUDE_VEX_VPROT_H

#define VPROT_NONE  0x0000
#define VPROT_READ  0x0001
#define VPROT_WRITE 0x0002
#define VPROT_EXEC  0x0004
#define VPROT_USER  0x0008

#define VPROT_RW    VPROT_READ | VPROT_WRITE
#define VPROT_RWX   VPROT_READ | VPROT_WRITE | VPROT_EXEC
#define VPROT_RX    VPROT_READ | VPROT_EXEC

#define VPROT_URW   VPROT_USER | VPROT_READ | VPROT_WRITE
#define VPROT_URWX  VPROT_USER | VPROT_READ | VPROT_WRITE | VPROT_EXEC
#define VPROT_URX   VPROT_USER | VPROT_READ | VPROT_EXEC

#endif /* INCLUDE_VEX_VPROT_H */
