#ifndef _VEX_VPROT_H
#define _VEX_VPROT_H 1

#define VPROT_NONE  0x0000U
#define VPROT_READ  0x0001U
#define VPROT_WRITE 0x0002U
#define VPROT_EXEC  0x0004U
#define VPROT_USER  0x0008U

#define VPROT_RW  VPROT_READ | VPROT_WRITE
#define VPROT_RWX VPROT_READ | VPROT_WRITE | VPROT_EXEC
#define VPROT_RX  VPROT_READ | VPROT_EXEC

#define VPROT_URW  VPROT_USER | VPROT_READ | VPROT_WRITE
#define VPROT_URWX VPROT_USER | VPROT_READ | VPROT_WRITE | VPROT_EXEC
#define VPROT_URX  VPROT_USER | VPROT_READ | VPROT_EXEC

#endif
