sources += arch/x86_64/kernel/gdt.c
sources += arch/x86_64/kernel/idt.c
sources += arch/x86_64/kernel/idts.S
sources += arch/x86_64/kernel/init.c
sources += arch/x86_64/kernel/ireq.c
sources += arch/x86_64/kernel/pic.c
