## SPDX-License-Identifier: BSD-2-Clause

SOURCES += arch/x86_64/kern/8259.c
SOURCES += arch/x86_64/kern/bxcon.c
SOURCES += arch/x86_64/kern/gdt.c
SOURCES += arch/x86_64/kern/idt.c
SOURCES += arch/x86_64/kern/idt_thunks.S
SOURCES += arch/x86_64/kern/intreq.c
SOURCES += arch/x86_64/kern/setup.c
