## SPDX-License-Identifier: BSD-2-Clause
## Copyright (c) 2023, KanOS Contributors

SOURCES += lib/ctype/ctype.c

SOURCES += lib/inttypes/strtoimax.c
SOURCES += lib/inttypes/strtoumax.c

SOURCES += lib/pfmt/pfmt.c
SOURCES += lib/pfmt/vpfmt.c

SOURCES += lib/stdio/snprintf.c
SOURCES += lib/stdio/sprintf.c
SOURCES += lib/stdio/vsnprintf.c
SOURCES += lib/stdio/vsprintf.c

SOURCES += lib/stdlib/abs.c
SOURCES += lib/stdlib/atoi.c
SOURCES += lib/stdlib/atol.c
SOURCES += lib/stdlib/atoll.c
SOURCES += lib/stdlib/labs.c
SOURCES += lib/stdlib/llabs.c
SOURCES += lib/stdlib/strtol.c
SOURCES += lib/stdlib/strtoll.c
SOURCES += lib/stdlib/strtoul.c
SOURCES += lib/stdlib/strtoull.c
SOURCES += lib/stdlib/strtousize.c

SOURCES += lib/string/memchr.c
SOURCES += lib/string/memcmp.c
SOURCES += lib/string/memcpy.c
SOURCES += lib/string/memset.c
SOURCES += lib/string/strcat.c
SOURCES += lib/string/strchr.c
SOURCES += lib/string/strcmp.c
SOURCES += lib/string/strcpy.c
SOURCES += lib/string/strcspn.c
SOURCES += lib/string/strerror.c
SOURCES += lib/string/strerror_r.c
SOURCES += lib/string/strlen.c
SOURCES += lib/string/strncat.c
SOURCES += lib/string/strncmp.c
SOURCES += lib/string/strncpy.c
SOURCES += lib/string/strnlen.c
SOURCES += lib/string/strpbrk.c
SOURCES += lib/string/strrchr.c
SOURCES += lib/string/strspn.c
SOURCES += lib/string/strstr.c

SOURCES += lib/strings/kstrncat.c
SOURCES += lib/strings/kstrncpy.c
SOURCES += lib/strings/strcasecmp.c
SOURCES += lib/strings/strncasecmp.c
