## SPDX-License-Identifier: BSD-2-Clause
## Copyright (c) 2023, KanOS Contributors

SOURCES += libkern/ctype/ctype.c

SOURCES += libkern/inttypes/strtoimax.c
SOURCES += libkern/inttypes/strtoumax.c

SOURCES += libkern/pfmt/pfmt.c
SOURCES += libkern/pfmt/vpfmt.c

SOURCES += libkern/stdio/snprintf.c
SOURCES += libkern/stdio/sprintf.c
SOURCES += libkern/stdio/vsnprintf.c
SOURCES += libkern/stdio/vsprintf.c

SOURCES += libkern/stdlib/abs.c
SOURCES += libkern/stdlib/atoi.c
SOURCES += libkern/stdlib/atol.c
SOURCES += libkern/stdlib/atoll.c
SOURCES += libkern/stdlib/labs.c
SOURCES += libkern/stdlib/llabs.c
SOURCES += libkern/stdlib/strtol.c
SOURCES += libkern/stdlib/strtoll.c
SOURCES += libkern/stdlib/strtoul.c
SOURCES += libkern/stdlib/strtoull.c
SOURCES += libkern/stdlib/strtousize.c

SOURCES += libkern/string/memchr.c
SOURCES += libkern/string/memcmp.c
SOURCES += libkern/string/memcpy.c
SOURCES += libkern/string/memset.c
SOURCES += libkern/string/strcat.c
SOURCES += libkern/string/strchr.c
SOURCES += libkern/string/strcmp.c
SOURCES += libkern/string/strcpy.c
SOURCES += libkern/string/strcspn.c
SOURCES += libkern/string/strerror.c
SOURCES += libkern/string/strerror_r.c
SOURCES += libkern/string/strlen.c
SOURCES += libkern/string/strncat.c
SOURCES += libkern/string/strncmp.c
SOURCES += libkern/string/strncpy.c
SOURCES += libkern/string/strnlen.c
SOURCES += libkern/string/strpbrk.c
SOURCES += libkern/string/strrchr.c
SOURCES += libkern/string/strspn.c
SOURCES += libkern/string/strstr.c

SOURCES += libkern/strings/kstrncat.c
SOURCES += libkern/strings/kstrncpy.c
SOURCES += libkern/strings/strcasecmp.c
SOURCES += libkern/strings/strncasecmp.c
