## SPDX-License-Identifier: GPL-2.0-only

SOURCES += libkern/ctype/ctype.c

SOURCES += libkern/format/format.c
SOURCES += libkern/format/vformat.c

SOURCES += libkern/sprintf/snprintf.c
SOURCES += libkern/sprintf/sprintf.c
SOURCES += libkern/sprintf/vsnprintf.c
SOURCES += libkern/sprintf/vsprintf.c

SOURCES += libkern/stdlib/strtoimax.c
SOURCES += libkern/stdlib/strtol.c
SOURCES += libkern/stdlib/strtoll.c
SOURCES += libkern/stdlib/strtoul.c
SOURCES += libkern/stdlib/strtoull.c
SOURCES += libkern/stdlib/strtoumax.c
SOURCES += libkern/stdlib/strtousize.c

SOURCES += libkern/string/memchr.c
SOURCES += libkern/string/memcmp.c
SOURCES += libkern/string/memcpy.c
SOURCES += libkern/string/memset.c
SOURCES += libkern/string/strcat.c
SOURCES += libkern/string/strchr.c
SOURCES += libkern/string/strcmp.c
SOURCES += libkern/string/strcpy.c
SOURCES += libkern/string/strcspn.c
SOURCES += libkern/string/strerror.c
SOURCES += libkern/string/strerror_r.c
SOURCES += libkern/string/strlen.c
SOURCES += libkern/string/strncat.c
SOURCES += libkern/string/strncmp.c
SOURCES += libkern/string/strncpy.c
SOURCES += libkern/string/strnlen.c
SOURCES += libkern/string/strpbrk.c
SOURCES += libkern/string/strrchr.c
SOURCES += libkern/string/strspn.c
SOURCES += libkern/string/strstr.c

SOURCES += libkern/strings/kstrncat.c
SOURCES += libkern/strings/kstrncpy.c
SOURCES += libkern/strings/strcasecmp.c
SOURCES += libkern/strings/strncasecmp.c
