#!/bin/sh

printf "/* AUTOGENERATED */\n"

printf "#ifndef __PUBLIC_KANERU_VERSION_H__\n"
printf "#define __PUBLIC_KANERU_VERSION_H__\n"

printf "#define KANERU_VERSION_MAJOR ${1}\n"
printf "#define KANERU_VERSION_MINOR ${2}\n"
printf "#define KANERU_VERSION_PATCH ${3}\n"
printf "#define KANERU_VERSION_METADATA 0x${4}\n"

if [ "${5}" = "none" ]; then
    printf "#define KANERU_VERSION_POSTFIX ((void *)0)\n"
    printf "#define KANERU_SEMVER_STR \"${1}.${2}.${3}+${4}\n"
else
    printf "#define KANERU_VERSION_POSTFIX \"${5}\"\n"
    printf "#define KANERU_SEMVER_STR \"${1}.${2}.${3}-${5}+${4}\"\n"
fi

printf "#endif /* __PUBLIC_KANERU_VERSION_H__ */\n"
