/* SPDX-License-Identifier: Zlib */
#ifndef UAPI_VEX_ERRNO_H
#define UAPI_VEX_ERRNO_H

#define _k_EDOM             101
#define _k_EILSEQ           102
#define _k_ERANGE           103

#define _k_E2BIG            201
#define _k_EACCES           202
#define _k_EADDRINUSE       203
#define _k_EADDRNOTAVAIL    204
#define _k_EAFNOSUPPORT     205
#define _k_EAGAIN           206
#define _k_EALREADY         207
#define _k_EBADF            208
#define _k_EBADMSG          209
#define _k_EBUSY            210
#define _k_ECANCELED        211
#define _k_ECHILD           212
#define _k_ECONNABORTED     213
#define _k_ECONNREFUSED     214
#define _k_ECONNRESET       215
#define _k_EDEADLK          216
#define _k_EDESTADDRREQ     217
#define _k_EDQUOT           218
#define _k_EEXIST           219
#define _k_EFAULT           220
#define _k_EFBIG            221
#define _k_EHOSTUNREACH     222
#define _k_EIDRM            223
#define _k_EINPROGRESS      224
#define _k_EINTR            225
#define _k_EINVAL           226
#define _k_EIO              227
#define _k_EISCONN          228
#define _k_EISDIR           229
#define _k_ELOOP            230
#define _k_EMFILE           231
#define _k_EMLINK           232
#define _k_EMSGSIZE         233
#define _k_EMULTIHOP        234
#define _k_ENAMETOOLONG     235
#define _k_ENETDOWN         236
#define _k_ENETRESET        237
#define _k_ENETUNREACH      238
#define _k_ENFILE           239
#define _k_ENOBUFS          240
#define _k_ENODATA          241
#define _k_ENODEV           242
#define _k_ENOENT           243
#define _k_ENOEXEC          244
#define _k_ENOLCK           245
#define _k_ENOLINK          246
#define _k_ENOMEM           247
#define _k_ENOMSG           248
#define _k_ENOPROTOOPT      249
#define _k_ENOSPC           250
#define _k_ENOSR            251
#define _k_ENOSTR           252
#define _k_ENOSYS           253
#define _k_ENOTCONN         254
#define _k_ENOTDIR          255
#define _k_ENOTEMPTY        256
#define _k_ENOTSOCK         257
#define _k_ENOTSUP          258
#define _k_ENOTTY           259
#define _k_ENXIO            260
#define _k_EOPNOTSUPP       261
#define _k_EOVERFLOW        262
#define _k_EPERM            263
#define _k_EPIPE            264
#define _k_EPROTO           265
#define _k_EPROTONOSUPPORT  266
#define _k_EPROTOTYPE       267
#define _k_EROFS            268
#define _k_ESPIPE           269
#define _k_ESRCH            270
#define _k_ESTALE           271
#define _k_ETIME            272
#define _k_ETIMEDOUT        273
#define _k_ETXTBSY          274
#define _k_EWOULDBLOCK      275
#define _k_EXDEV            276

#endif /* UAPI_VEX_ERRNO_H */
