#ifndef _UAPI_VEX_ERRNO_H
#define _UAPI_VEX_ERRNO_H 1

#define __k_EDOM   101
#define __k_EILSEQ 102
#define __k_ERANGE 103

#define __k_E2BIG           201
#define __k_EACCES          202
#define __k_EADDRINUSE      203
#define __k_EADDRNOTAVAIL   204
#define __k_EAFNOSUPPORT    205
#define __k_EAGAIN          206
#define __k_EALREADY        207
#define __k_EBADF           208
#define __k_EBADMSG         209
#define __k_EBUSY           210
#define __k_ECANCELED       211
#define __k_ECHILD          212
#define __k_ECONNABORTED    213
#define __k_ECONNREFUSED    214
#define __k_ECONNRESET      215
#define __k_EDEADLK         216
#define __k_EDESTADDRREQ    217
#define __k_EDQUOT          218
#define __k_EEXIST          219
#define __k_EFAULT          220
#define __k_EFBIG           221
#define __k_EHOSTUNREACH    222
#define __k_EIDRM           223
#define __k_EINPROGRESS     224
#define __k_EINTR           225
#define __k_EINVAL          226
#define __k_EIO             227
#define __k_EISCONN         228
#define __k_EISDIR          229
#define __k_ELOOP           230
#define __k_EMFILE          231
#define __k_EMLINK          232
#define __k_EMSGSIZE        233
#define __k_EMULTIHOP       234
#define __k_ENAMETOOLONG    235
#define __k_ENETDOWN        236
#define __k_ENETRESET       237
#define __k_ENETUNREACH     238
#define __k_ENFILE          239
#define __k_ENOBUFS         240
#define __k_ENODATA         241
#define __k_ENODEV          242
#define __k_ENOENT          243
#define __k_ENOEXEC         244
#define __k_ENOLCK          245
#define __k_ENOLINK         246
#define __k_ENOMEM          247
#define __k_ENOMSG          248
#define __k_ENOPROTOOPT     249
#define __k_ENOSPC          250
#define __k_ENOSR           251
#define __k_ENOSTR          252
#define __k_ENOSYS          253
#define __k_ENOTCONN        254
#define __k_ENOTDIR         255
#define __k_ENOTEMPTY       256
#define __k_ENOTSOCK        257
#define __k_ENOTSUP         258
#define __k_ENOTTY          259
#define __k_ENXIO           260
#define __k_EOPNOTSUPP      261
#define __k_EOVERFLOW       262
#define __k_EPERM           263
#define __k_EPIPE           264
#define __k_EPROTO          265
#define __k_EPROTONOSUPPORT 266
#define __k_EPROTOTYPE      267
#define __k_EROFS           268
#define __k_ESPIPE          269
#define __k_ESRCH           270
#define __k_ESTALE          271
#define __k_ETIME           272
#define __k_ETIMEDOUT       273
#define __k_ETXTBSY         274
#define __k_EWOULDBLOCK     275
#define __k_EXDEV           276

#endif
