sources += libk/bitmap.c
sources += libk/ctype.c
sources += libk/format.c
sources += libk/hrsize.c
sources += libk/sprintf.c
sources += libk/stdlib.c
sources += libk/string.c
sources += libk/strings.c
