## SPDX-License-Identifier: BSD-2-Clause

SOURCES += libk/bitmap/bitmap.c

SOURCES += libk/ctype/ctype.c

SOURCES += libk/format/format.c
SOURCES += libk/format/vformat.c

SOURCES += libk/sprintf/snprintf.c
SOURCES += libk/sprintf/sprintf.c
SOURCES += libk/sprintf/vsnprintf.c
SOURCES += libk/sprintf/vsprintf.c

SOURCES += libk/stdlib/strtoimax.c
SOURCES += libk/stdlib/strtol.c
SOURCES += libk/stdlib/strtoll.c
SOURCES += libk/stdlib/strtoul.c
SOURCES += libk/stdlib/strtoull.c
SOURCES += libk/stdlib/strtoumax.c
SOURCES += libk/stdlib/strtousize.c

SOURCES += libk/string/memchr.c
SOURCES += libk/string/memcmp.c
SOURCES += libk/string/memcpy.c
SOURCES += libk/string/memset.c
SOURCES += libk/string/strcat.c
SOURCES += libk/string/strchr.c
SOURCES += libk/string/strcmp.c
SOURCES += libk/string/strcpy.c
SOURCES += libk/string/strcspn.c
SOURCES += libk/string/strerror.c
SOURCES += libk/string/strerror_r.c
SOURCES += libk/string/strlen.c
SOURCES += libk/string/strncat.c
SOURCES += libk/string/strncmp.c
SOURCES += libk/string/strncpy.c
SOURCES += libk/string/strnlen.c
SOURCES += libk/string/strpbrk.c
SOURCES += libk/string/strrchr.c
SOURCES += libk/string/strspn.c
SOURCES += libk/string/strstr.c

SOURCES += libk/strings/kstrncat.c
SOURCES += libk/strings/kstrncpy.c
SOURCES += libk/strings/strcasecmp.c
SOURCES += libk/strings/strncasecmp.c
